#!/usr/bin/python

import re, sys, os, time, StringIO, subprocess
import xml.etree.ElementTree as ET

cmd = "tail -1000 /var/log/HPCCSystems/*roxie*/roxie.log"
run_it = os.popen(cmd).readlines()

for i in run_it:
        if re.search('suspended',  i):
                print i.strip('\n')
                sys.exit(2)

