#!/bin/bash

thorgroup="/var/lib/HPCCSystems/*thor*/thorgroup.slave"
roxiegroup="/var/lib/HPCCSystems/*roxie*/slaves"

for i in $thorgroup
	do 
		if [ -f $i ]
		then
			cat $i | awk -F':' '{printf "%s,",$1} END {print ""}' | rev | cut -c 2- | rev
			break
		else
			cat $roxiegroup | awk '{printf "%s,",$1} END {print ""}' | rev | cut -c 2- | rev
			break
		fi
	done
