#!/bin/bash

BadStatus=$(service hpcc-init status|grep eclccserver|grep stopped|tail -1|awk '{print $NF}')
GoodStatus=$(service hpcc-init status|grep eclccserver|grep running|tail -1|awk '{print $NF}')

if [ $BadStatus == 'stopped...' ]
then
	echo "is stopped"
elif [ $GoodStatus == 'running...' ]
then
	echo "is running"
fi

