#!/bin/bash

status=$(service hpcc-init -c eclserver status|tail -1|grep eclserver|grep -v grep|awk '{print $NF}')

for state in $status
do 
	if [ $status == 'stopped...' ]
	then
		echo "is stopped"
	elif [ $status == 'running...' ]
	then
		echo 'is running'
	fi
done
