#!/bin/bash

BadStatus=$(service hpcc-init -c eclserver status|grep stopped|tail -1|awk '{print $(NF - 1)}')
GoodStatus=$(service hpcc-init -c eclserver status|grep running|tail -1|awk '{print $(NF - 1)}')

if [[ $BadStatus == 'stopped' ]]
then
	echo "is stopped"
elif [[ $GoodStatus == 'running' ]]
then
	echo "is running"
fi

