#!/bin/bash

host=$(hostname -i)
running_slaves=$(ps ax|grep thor|egrep -v "roxiepipe|backupnode|view|less"|grep -vc grep)
conf_slaves=$(cat /var/lib/HPCCSystems/*thor*/thorgroup.slave |sort -u|grep -wc "$host")

if [ $running_slaves == $conf_slaves ]
then
        echo "$running_slaves thorslaves processes are running"
else
        echo "A ThorSlave process might be down showing $running_slaves instead of $conf_slaves"
fi

